/**
 * Openfirm API
 * This is a sandbox server.  You can find out more about Openfirm [here](/docs).  For this sample, you can use the api key `test` to test the authorization filters.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: kameronkales@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import ApiResponse from './model/ApiResponse';
import MerchantQueue from './model/MerchantQueue';
import Pong from './model/Pong';
import QueueTransaction from './model/QueueTransaction';
import StatusApi from './api/StatusApi';
import TransactionsApi from './api/TransactionsApi';


/**
* This_is_a_sandbox_server___You_can_find_out_more_about_Openfirm__here__docs___For_this_sample_you_can_use_the_api_key_test_to_test_the_authorization_filters_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var OpenfirmApi = require('index'); // See note below*.
* var xxxSvc = new OpenfirmApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new OpenfirmApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new OpenfirmApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new OpenfirmApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.0.1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The ApiResponse model constructor.
     * @property {module:model/ApiResponse}
     */
    ApiResponse,

    /**
     * The MerchantQueue model constructor.
     * @property {module:model/MerchantQueue}
     */
    MerchantQueue,

    /**
     * The Pong model constructor.
     * @property {module:model/Pong}
     */
    Pong,

    /**
     * The QueueTransaction model constructor.
     * @property {module:model/QueueTransaction}
     */
    QueueTransaction,

    /**
    * The StatusApi service constructor.
    * @property {module:api/StatusApi}
    */
    StatusApi,

    /**
    * The TransactionsApi service constructor.
    * @property {module:api/TransactionsApi}
    */
    TransactionsApi
};
